# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66a171a98f1a2c22fd866e6475c995421cd725b9cd1728bcd73532a0e966c6ec361d7c61dc7638c000151ef5341bf418cf212407dfe3a90cb40e5a7138ee0aeb
  api_url: https://stapp.sendaguy.com/api
  host: 'http://localhost:3000'

test:
  secret_key_base: 85ae087f2fdf4297966414ed2af6ec2955eb54595eb35036471d4e5bac6543859ef5f6ca1cfd5b7d3862842ba741b42535851aecda24f5e7d23c3afe65a63116
  api_url: https://stapp.sendaguy.com/api
  host: 'http://localhost:3000'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api_url: <%= ENV["API_URL"] %>
  host: <%= ENV["APP_URL"] %>
